<?php
include_once('cta-1/functions.php');
include_once("cta-2/functions.php");
include_once("cta-3/functions.php");
include_once("cta-4/functions.php");
include_once("post-grid-1/functions.php");
include_once("post-grid-2/functions.php");
include_once("header-1/functions.php");
include_once("tif-search-modal/functions.php");
include_once("tif-featherlight-slider/functions.php");
